# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Delploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    
    - run: mkdir ./target

    - name: Build with Maven
      run: mvn -f app/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./app/target/app-0.1.0.jar ./target  

    - name: Build with Maven
      run: mvn -f app2/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./app2/target/app2-0.1.0.jar ./target  

    - run: cp docker-compose.yml ./target  
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with: 
        name: app
        path: ./target/
    
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build, ]
    steps:
    - name: Download app artifacts
      uses: actions/download-artifact@v1
      with:
        name: app
    - name: Copy host via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        PORT: 22
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
      with:
        source: "app/*"
        target: "/home/${{ secrets.SSH_USER }}/"
        strip_components: 1
        rm: false
        overwrite: true

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        PORT: 22
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.SSH_USER }}/
          touch acme.json
          sudo chmod 0600 acme.json
          sudo echo "PUB_IP=${{ secrets.SSH_HOST }}" | sed -e 's/\./-/g' > .env
          sudo docker-compose up -d
    
    
        
